name: fantasy-winner
region: nyc
services:
  - name: web
    github:
      repo: yahelc/fantasy-winner
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /
